### ISSUE TITLE
Can't seem to use go get on /rest

### ISSUE THREAD

**Issue by marcolussetti** [ns1/ns1-go#104]
Can't seem to get the `rest` sub-package. At first I thought it was likely user error on my part, but I'm not so sure anymore.

Updated description/cause:

v2.4.0 from 28 days ago (https://github.com/ns1/ns1-go/releases/tag/v2.4.0) seems to be pointing to the wrong commit:
https://github.com/ns1/ns1-go/commit/7c167e5c28b7b40d82fb3d954daf7bfd55f9c6e2 which is from 2016 (really a v1 commit?)

Take a peek inside go/src/gopkg.in/ns1/ns1-go.v2 at the git repo:
![image](https://user-images.githubusercontent.com/15794684/86159599-7143a580-babf-11ea-9d51-b855eeb13826.png)

Original notes:

```
C:\Users\REMOVED>go get gopkg.in/ns1/ns1-go.v2/rest
package gopkg.in/ns1/ns1-go.v2/rest: cannot find package "gopkg.in/ns1/ns1-go.v2/rest" in any of:
        c:\go\src\gopkg.in\ns1\ns1-go.v2\rest (from $GOROOT)
        C:\Users\REMOVED\go\src\gopkg.in\ns1\ns1-go.v2\rest (from $GOPATH)
```

And if I check in the directory, it is indeed missing the rest directory:
![image](https://user-images.githubusercontent.com/15794684/86159120-b0252b80-babe-11ea-87b5-43eb86ba376a.png)

Tried combinations of fetching package first, then subpackage, and viceversa. It seems like the issue is actually related to release tagging.

**Comment by marcolussetti** [comment]
Also seems like it's pointing to the master branch which is from 2016, rather than v2.

**Comment by Zach-Johnson** [comment]
@marcolussetti thanks for bringing this to our attention - it looks like we did indeed mis-tag our last release. I've just pushed up tag v2.4.1, which should be correct now. I'm going to close this issue, but feel free to re-open if you still encounter problems!
