### ISSUE TITLE
License discrepancy with https://pkg.go.dev/

### ISSUE THREAD

**Issue by SelfDrivingCarp** [ns1/ns1-go#117]
https://pkg.go.dev/ is the new system for browsing package documentation.

https://pkg.go.dev/gopkg.in/ns1/ns1-go.v2 to read this package because of a discrepancy with the license. The license file is there in a file name the site expects so there must be a discrepancy with the license text.

The license policy is here: https://pkg.go.dev/license-policy

**Comment by pcatalini** [comment]
@jasonmf  Thank you for reporting this issue.
We already added this to our backlog.

**Comment by eravin-ns1** [comment]
The doc page at https://pkg.go.dev/gopkg.in/ns1/ns1-go.v2 now works properly.
