### ISSUE TITLE
Creating a V2... more breaking changes :( 

### ISSUE THREAD

**Issue by pashap** [ns1/ns1-go#12]
This issue is a continuation of PR #11.

So, I have made some breaking changes while iterating over the rest client, which I know is pretty anti-go(or any open source project for that matter). 

@bobtfish had a great suggestion of utilizing [gopkg](http://labix.org/gopkg.in):
  1. We would branch off the current `master` into a `v1`. 
     - We can do this right away and it shouldnt affect current users
     - both `go get github.com/ns1/ns1-go` and `go get gopkg.in/ns1/ns1-go.v1` should work
  2. When we come to a consensus on the `develop` branch, we can branch that off into a `v2`
    - This will break users of `v1` that are still using `import "github.com/ns1/ns1-go"`. but they will just need to update to `import "gopkg.in/ns1/ns1-go.v1"`
   

I could be wrong, but I believe that the disadvantages of gopkg are:
  - Builds are not versioned/reproducible. Only the `go get` command is enhanced to respect versioning.
  - We are relying on the gopkg hosted static site(this may not matter at all, just noting it)

_note: I made a `v1` tag this morning on `master`, but in hindsight, that shouldve been a branch named `v1`(which I can still do)._

I need to update the readme of `v1` so that it states the future `v2`/`develop` branch version is coming, and that users should update their import paths when possible. Im thinking a time table of getting the `v2` branch created by the end of the month.

Also PR #7 breaking changes are included in the develop branch. I think we can close that. Does that sound okay @josephholsten?

Regarding the corresponding [terraform provider](https://github.com/bobtfish/terraform-provider-nsone), can we wait until `v2` has been created to add additional work to it?

Thanks again @bobtfish and @sarguru for the help and patience in migrating this repo to the `ns1` organization.

**Comment by josephholsten** [comment]
Ensighten has been working on an build of terraform with the nsone provider in our local fork, I'd love to get the latest and greatest released in whatever form.

If you apply the changes, I'll get an updated nsone provider branch up asap.

**Comment by pashap** [comment]
Sorry for the wait @josephholsten 

V2 is ready for release, i am still working on documentation and more features/functionality, but i believe it's in decent enough shape to start the terraform provider implementation. 

I can merge develop into master and tag a 2.0.0 release tonight.

**Comment by pashap** [comment]
I ended up creating a `v2` and `v2-unstable` branch, and plan on making `v2` the default branch tomorrow unless any objections.

**Comment by pashap** [comment]
Just made v2 the default branch. Still working on a readme and getting the status checks running in travisci again.

@josephholsten Is it still possible to get an updated ns1 provider branch going?

**Comment by josephholsten** [comment]
@pashap absolutely! We've internally been using a 0.6 fork to maintain our provider fork. I'll try to get it updated to v2, then push an 0.7 PR in the next week.

**Comment by pashap** [comment]
Thats great, please lmk if there's any way i can help.
