### ISSUE TITLE
More sensical error logging

### ISSUE THREAD

**Issue by AskAlice** [ns1/ns1-go#134]
We have to override this package in order to log out the response body of bad responses [because it gets closed within ns1-go](https://github.com/ns1/ns1-go/blob/v2/rest/client.go#L162-L188) (and can not be read after it gets closed)

Rather than just returning an unmarshaling error, why not also pass along the response body?

**Comment by lfavaro-daitan** [comment]
Pull request already created related to that https://github.com/ns1/ns1-go/pull/137
@AskAlice we left a comment for you there on the PR.

**Comment by eravin-ns1** [comment]
This is fixed via PR #177 and released in v2.7.2.
