### ISSUE TITLE
Zone record json struct tag inconsistent casing

### ISSUE THREAD

**Issue by Ivan-Z** [ns1/ns1-go#141]
For the domain property on the zone record struct, why is the JSON tag capitalized? 
https://github.com/ns1/ns1-go/blob/v2/rest/model/dns/zone.go#L59
It is inconsistent with the rest of the code base, and breaks some code-gen tools when trying to integrate with the ns1-go package.

**Comment by ThiagoYU** [comment]
@Ivan-Z Thank you for reporting this issue. 
We already added this to our backlog.

**Comment by eravin-ns1** [comment]
Hi Ivan, it's definitely inconsistent and not ideal, but changing it might cause trouble for anyone with code that uses marshal/unmarshal on that struct.

Can you give us more details on the code-gen tools that were having trouble integrating with ns1-go? Were you able to find workarounds?

**Comment by jfarrell-NS1** [comment]
This fix will go out with the next version bump
