### ISSUE TITLE
intra-package imports don't use gopkg.in

### ISSUE THREAD

**Issue by josephholsten** [ns1/ns1-go#16]
Files in `gopkg.in/ns1/ns1-go.v2/rest` are currently `import`ing:

```
"github.com/ns1/ns1-go/rest/model/data"
"github.com/ns1/ns1-go/rest/model/account"
"github.com/ns1/ns1-go/rest/model/dns"
"github.com/ns1/ns1-go/rest/model/monitor"
```

Is this intentional?

**Comment by pashap** [comment]
@josephholsten That wasnt intentional, totally didnt realize it. should be 

```
"github.com/ns1/ns1-go.v2/rest/model/data"
"github.com/ns1/ns1-go.v2/rest/model/account"
"github.com/ns1/ns1-go.v2/rest/model/dns"
"github.com/ns1/ns1-go.v2/rest/model/monitor"
```

right?

**Comment by pashap** [comment]
or is the package structure poorly designed? it seems like there are a lot of imports for a rest client library, and the `model` package may not be necessary 

edit: just read the title, sorry. ill get a PR up with the fix :)
