### ISSUE TITLE
Should APIKeysService have Create/Get/Update/Delete?

### ISSUE THREAD

**Issue by josephholsten** [ns1/ns1-go#17]
in v1, `nsone.APIClient` had:
- `GetApikey(id string) (Apikey, error)`
- `CreateApikey(k *Apikey) error`
- `DeleteApikey(id string) error`
- `UpdateApikey(k *Apikey) error`

in v2, `rest.APIKeysService` has
- `List() ([]*account.APIKey, *http.Response, error)`

Should we add the rest of the CRUD like the other services? I don't personally use them, but the terraform provider has a resource for managing them.

**Comment by pashap** [comment]
Good point, we should add those for the terraform provider. i can get these added tonight and some other endpoints that are missing implemented/released tomorrow if thats cool?
