### ISSUE TITLE
rest.(*RecordService).Get(): panic: interface conversion: error is *json.SyntaxError, not *rest.Error

### ISSUE THREAD

**Issue by josephholsten** [ns1/ns1-go#22]
I'm getting:

```
panic: interface conversion: error is *json.SyntaxError, not *rest.Error
```

from `gopkg.in/ns1/ns1-go.v2/rest.(*RecordsService).Get()`

Looks like it's happening at https://github.com/ns1/ns1-go/blob/v2/rest/record.go#L28

**Comment by pashap** [comment]
it looks like the service isnt supporting arbitrary error types when checking the error returned from the http client. still looking into and trying to reproduce.

im thinking atm, something like this, but feels wrong with so many indentations:

```
    resp, err := s.client.Do(req, &r)
    if err != nil {
        if merr, ok := err.(*Error).Message; ok {
                  if merr.Message == "record not found" {
                            return nil, resp, ErrRecordMissing
                  }
        }
        return nil, resp, err
    }
```

**Comment by josephholsten** [comment]
I put together a patch using `switch err.(type)` instead of checking the cast. Do you have a preference?

**Comment by pashap** [comment]
Thats way better than what i was thinking! thank you, merging it now.
