### ISSUE TITLE
attempting to create records with 2.7.13 returns 500

### ISSUE THREAD

**Issue by costasd** [ns1/ns1-go#224]
Hi,

I'm co-maintaining [dnscontrol's](https://github.com/StackExchange/dnscontrol) ns1 support - which uses ns1-go under the hood.

It seems that 2.7.13 that is available as latest via gopkg is getting 500 from NS1's API when attempting to create or update any records. Unfortunately given that it's a 500, I don't get any more info about what's wrong.

Downgrading to 2.7.12 triggers the issue with tags/blocked_tags, so can't really say if that's an issue in 2.7.12 as well. It seems though, that 2.7.11 is working correctly against the API, so it's definitely something post 2.7.11.

Any combination of nil for tags/blocked_tags doesn't seem to help.

Not sure what more info I can provide, but happy to try anything, i can reproduce it every time in my setup.

thanks!

**Comment by pburrows-ns1** [comment]
Hi @costasd 

Yes, I can reproduce this too and it's related to the tags/blocked tags changes that were made.

Using `v2.7.11` there is no `tags` or `blocked_tags` in the `POST` body.

Using `v2.7.12` we have this:
```
"blocked_tags":null
```
Which results in `400 - tags and blocked_tags must be updated together`

Using `v2.7.13` we have this:
```
"tags":null,
"blocked_tags":null
```
Which results in `500 - Internal server error`

I will open an internal bug ticket to investigate more and will update this issue with any further info.

Thanks for reporting this!
