### ISSUE TITLE
Public feature roadmap

### ISSUE THREAD

**Issue by grantseltzer** [ns1/ns1-go#30]
Seems like a cool project, would be good to have something to point community members in the right direction for contributions

**Comment by mburtless** [comment]
Hi @grantseltzer - I've just joined NS1 and will be helping to maintain the repo moving forward.  Apologies for the delayed response and thanks for the interest in the project and the feedback!

I'm starting to build out a formal backlog of enhancements for NS1's open source projects now.  When this is complete I should be able to update the README with a roadmap, or at a minimum a list of TODO's, for this project.

**Comment by grantseltzer** [comment]
Really great to hear it @mburtless! Thanks for the comment, even despite the delay :-)

**Comment by Zach-Johnson** [comment]
@grantseltzer we're adding contribution guidelines in https://github.com/ns1/ns1-go/pull/94 so I'm going to go ahead and close out this issue. Thanks!
