### ISSUE TITLE
Move error message parsing to Client.Do

### ISSUE THREAD

**Issue by pashap** [ns1/ns1-go#35]
Right now, several endpoint handler methods repeat a common pattern of checking the response message for specific error messages. eg:

[GET Record](https://github.com/ns1/ns1-go/blob/v2/rest/record.go#L30)
```
if err.(*Error).Message == "record not found" {
   return nil, resp, ErrRecordMissing
}
```

[PUT Record](https://github.com/ns1/ns1-go/blob/v2/rest/record.go#L58-L61)
```
case "zone not found":
   return resp, ErrZoneMissing
case "record already exists":
   return resp, ErrRecordExists
```

As proposed by @captncraig in  https://github.com/ns1/ns1-go/pull/34#issue-215641557, we should probably move these checks into a central place like [Client.Do](https://github.com/ns1/ns1-go/blob/v2/rest/client.go#L137), or more specifically, in [CheckResponse](https://github.com/ns1/ns1-go/blob/v2/rest/client.go#L200).

**Comment by Zach-Johnson** [comment]
Hi @pashap - I'm going to close this issue due to the age and because we are taking on a larger refactor of this client that will likely encompass the suggestion you noted.
