### ISSUE TITLE
Stats API

### ISSUE THREAD

**Issue by derekargueta** [ns1/ns1-go#39]
I'd like to use this library to pull in QPS Reports, however the QPS code seems to be commented out. Is there any particular reason for this? I've hacked up [a functioning fork](https://github.com/derekargueta/ns1-go/commit/12d58e252a734c5ebcebc0673251ea51d569a050) temporarily for prototyping. If there's interest in bringing this functionality into the official client, I'd be happy to clean up my code and help out.

**Comment by stuffcarlcodes** [comment]
Hey Derek, this is awesome stuff! I'm going to circle back with our team and see if there was a deliberate cause for the original code to be commented out. Stay tuned!

**Comment by stuffcarlcodes** [comment]
Back-end team is reviewing the changes and seeing if it passes internal tests. We should be able to merge once that is completed. Thanks!

**Comment by pashap** [comment]
thanks @derekargueta , there is no reason for the comments(sorry about that). you are more than welcome to create a PR with that fork. it looks great to me, and i can review it when its created

**Comment by veshij** [comment]
@derekargueta did you have a chance to create a PR with stats changes?

**Comment by KlausVii** [comment]
Any chance someone on the team might pick this up? I'd guess derek has moved on.

**Comment by mburtless** [comment]
Hi all, I've just joined NS1 and will be helping to maintain the repo moving forward.

I've added this feature request to our backlog so it can be addressed.  In the mean time, if someone would like to contribute to this via a PR, I'd be more than happy to review it!

**Comment by veshij** [comment]
@mburtless please take a look at the PR.

**Comment by mburtless** [comment]
@veshij - Thanks for the PR, awesome contribution!  I should have some feedback for you on that shortly.

**Comment by veshij** [comment]
@mburtless any progress with review?

**Comment by mburtless** [comment]
@veshij - Sorry for the delay.  This is looking good, I just left a couple of requests in the PR for you to fix before we can merge.

**Comment by mburtless** [comment]
Closing out this issue as a `StatsService` for using retrieving the QPS stats has been added.  Please take a look at `rest/_examples/stats.go` for examples on using it.

Huge thanks to @veshij for the contribution!
