### ISSUE TITLE
DataFeedsService missing Publish method?

### ISSUE THREAD

**Issue by brycekahle** [ns1/ns1-go#53]
The equivalent of this endpoint: https://ns1.com/api#postpublish-data-from-a-data-source

**Comment by pashap** [comment]
Hi @brycekahle, I think this method covers that endpoint: https://github.com/ns1/ns1-go/blob/v2/rest/data_source.go#L112

I put the method on the `DataSourcesService` because it takes a datasource ID. But I now realize that probably just makes things a bit more confusing when referencing the docs.

**Comment by brycekahle** [comment]
Great. Thanks!
