### ISSUE TITLE
NS1 record to validate aws_acm_certificate fails - trailing dot

### ISSUE THREAD

**Issue by sam-caldwell** [ns1/ns1-go#79]
This issue is submitted to tie this project to the reported issue in the ns1 terraform provider where the initial problem was identified.  See [Initial Issue Report](https://github.com/terraform-providers/terraform-provider-ns1/issues/38).

1. The issue is confirmed by multiple sources.
2. The issue was originally found in November 2018 and confirmed by the reporter of this issue in November 2019.
3. Investigation shows root cause of the issue and a possible solution.

This issue is being reported to associate with a pull request shortly and is intended to close the loop between the two projects.

**Comment by sam-caldwell** [comment]
The following pull request is submitted to address this issue: https://github.com/ns1/ns1-go/pull/80.

Please let me know if there are any further questions.

**Comment by Zach-Johnson** [comment]
A separate PR was opened and merged to address this here: https://github.com/terraform-providers/terraform-provider-ns1/pull/97

**Comment by Zach-Johnson** [comment]
The PR mentioned above has been merged and released so I'm closing this issue.
