### ISSUE TITLE
Unable to create URLFWD records

### ISSUE THREAD

**Issue by ghost** [ns1/ns1-go#82]
When creating a new URLFWD record the API endpoint returns a "Invalid redirect mode for URLFWD record" error.

The Answer struct defines the RData as a string array.  The API endpoint on the other hand appears to be expecting an integer for the Type, Forwarding Mode, and Query Forwarding values.

```
newRecord := dns.NewRecord("mydomain.com", "fwd.mydomain.com", "URLFWD")
newRecord.TTL = 3600
newRecord.AddAnswer(dns.NewAnswer([]string{"/", "https://www.google.com", "301", "2", "0"}))
```

Generates the following json request:

```
{
  "meta": {},
  "zone": "mydomain.com",
  "domain": "fwd.mydomain.com",
  "type": "URLFWD",
  "ttl": 3600,
  "answers": [
    {
      "meta": {},
      "answer": [
        "/",
        "https://www.google.com",
        "301",
        "2",
        "0"
      ]
    }
  ],
  "filters": []
}
```

Submitting the same request with curl, but changing the answer array as follows succeeds.

```
      "answer": [
        "/",
        "https://www.google.com",
        301,
        2,
        0
      ]
```

**Comment by rupa** [comment]
Thanks for opening this issue. 

This sort of thing has come up before, so on the bright side some of the work done previously should help keep adding support pretty simple.

We'll want to add a `NewURLFWDAnswer` function that gets the values typed correctly for the API. We'll also need to ensure that the API response values get parsed back out correctly - there's a good chance that part will already work.

We'll get this work scheduled ASAP and I'll keep you posted.

**Comment by rupa** [comment]
https://github.com/ns1/ns1-go/pull/86 should take care of this :)
